#!/bin/bash

# Assign the first argument ($1) to a variable for readability
filename=$1

# Check if the user actually provided an argument
if [ -z "$filename" ]; then
    echo "Error: Please provide a file or directory name."
    exit 1
fi

if [ -f "$filename" ]; then
    echo "$filename is a regular file."
elif [ -d "$filename" ]; then
    echo "$filename is a directory."
else
    echo "$filename is another type of file or does not exist."
fi
