#!/bin/bash

file_path=$1

# Check if the user provided a filename
if [ -z "$file_path" ]; then
    echo "Error: Please provide a file path."
    exit 1
fi

# Check if file exists (-e)
if [ -e "$file_path" ]; then
    echo "$file_path passwords are enabled."

    # Check if we have write permission (-w)
    if [ -w "$file_path" ]; then
        echo "You have permissions to edit $file_path."
    else
        echo "You do NOT have permissions to edit $file_path"
    fi
else
    echo "The file '$file_path' does not exist."
fi
